### ISSUE TITLE
not working on api 19

### ISSUE THREAD

**Issue by dvillareal22** [florent37/AwesomeBar#5]
When I try to use the library and run the app on api level 19, the app crashes and pointing out on the vectordrawable on awesomebar.java

**Comment by florent37** [comment]
Juste enable the vector company from your build.gradle

Le 8 avr. 2017 03:02, "Daniel Villareal" <notifications@github.com> a
écrit :

**Comment by harmeetsingh-work** [comment]
Facing the same issue.
Using `vectorDrawables.useSupportLibrary = true` in my gradle still crashes the App.

```
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/awsb_ic_menu_white_24dp.png from xml type xml resource ID #0x7f080063
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2361)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2316)
        at android.content.res.Resources.getXml(Resources.java:988)
        at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:562)
        at android.support.graphics.drawable.AnimatedVectorDrawableCompat.inflate(AnimatedVectorDrawableCompat.java:458)
        at android.support.graphics.drawable.AnimatedVectorDrawableCompat.createFromXmlInner(AnimatedVectorDrawableCompat.java:250)
        at android.support.graphics.drawable.AnimatedVectorDrawableCompat.create(AnimatedVectorDrawableCompat.java:230)
        at com.github.florent37.awesomebar.AwesomeBar.<init>(AwesomeBar.java:93)
        at com.github.florent37.awesomebar.AwesomeBar.<init>(AwesomeBar.java:62)
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:595) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at com.cloudblocks.android.user.ui.MainActivity.onCreate(MainActivity.java:45) 
        at android.app.Activity.performCreate(Activity.java:5231) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.io.FileNotFoundException: Corrupt XML binary file
        at android.content.res.AssetManager.openXmlAssetNative(Native Method)
        at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:488)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2343)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2316) 
        at android.content.res.Resources.getXml(Resources.java:988) 
        at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:562) 
        at android.support.graphics.drawable.AnimatedVectorDrawableCompat.inflate(AnimatedVectorDrawableCompat.java:458) 
        at android.support.graphics.drawable.AnimatedVectorDrawableCompat.createFromXmlInner(AnimatedVectorDrawableCompat.java:250) 
        at android.support.graphics.drawable.AnimatedVectorDrawableCompat.create(AnimatedVectorDrawableCompat.java:230) 
        at com.github.florent37.awesomebar.AwesomeBar.<init>(AwesomeBar.java:93) 
        at com.github.florent37.awesomebar.AwesomeBar.<init>(AwesomeBar.java:62) 
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:595) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at com.cloudblocks.android.user.ui.MainActivity.onCreate(MainActivity.java:45) 
        at android.app.Activity.performCreate(Activity.java:5231) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
```

The solution for me was to import your library as module in my project and I added `vectorDrawables.useSupportLibrary = true` in your library gradle and no more crash.

**Comment by harmeetsingh-work** [comment]
On Kitkat 4.4.2

Now facing new issue
```
java.lang.NoClassDefFoundError: android.graphics.drawable.AnimatedVectorDrawable
        at com.github.florent37.awesomebar.ActionItem.tryToAnimate(ActionItem.java:81)
        at com.github.florent37.awesomebar.ActionItem.access$100(ActionItem.java:23)
        at com.github.florent37.awesomebar.ActionItem$1.onClick(ActionItem.java:55)
        at android.view.View.performClick(View.java:4640)
        at android.view.View$PerformClick.run(View.java:19431)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5598)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
```

Had to add a OS version check in `tryToAnimate` method, not optimised but working.

```
private boolean tryToAnimate(){
            final Drawable drawable = icon.getDrawable();
            if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                if (drawable instanceof AnimatedVectorDrawable) {
                    final AnimatedVectorDrawable d = (AnimatedVectorDrawable) drawable;
                    d.start();
                    return true;
                } else if (drawable instanceof AnimatedVectorDrawableCompat) {
                    final AnimatedVectorDrawableCompat d = (AnimatedVectorDrawableCompat) drawable;
                    d.start();
                    return true;
                }
            } else {
                if (drawable instanceof AnimatedVectorDrawableCompat) {
                    final AnimatedVectorDrawableCompat d = (AnimatedVectorDrawableCompat) drawable;
                    d.start();
                    return true;
                }
            }
            return false;
    }
```
